sudo: false
language: python
python:
  - 3.4
  - 3.5
  - 3.6

cache:
  pip: true

before_install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - pip install -e .
  - pip install coala-bears[alldeps] --pre -U
  # https://github.com/coala/coala-bears/issues/1037
  - >
    if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
      sed -i.bak '/bears = GitCommitBear/d' .coafile
    fi
  - coala --non-interactive

notifications:
  email: false

branches:
  exclude:
    - /^sils\//
